name: 360T7-hanwckf-mini

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      clean:
         description: 'clean ccache'
         default: 'false'
  
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Prepare environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
         sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo apt update
         sudo apt install binutils bzip2 diff find flex gawk gcc-6+ getopt grep install libc-dev libz-dev make4.1+ perl python3.6+ rsync subversion unzip which libncurses5-dev zlib1g-dev gawk gcc-multilib g++-multilib flex git-core gettext libssl-dev ocaml sharutils re2c -y
         sudo timedatectl set-timezone "Asia/Shanghai"
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
    
    - name: Clone source code
      working-directory: /workdir
      run: |
         df -hT $PWD
         git clone https://github.com/gl-inet/glinet4.x.git
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
    
    - name: Cache
      uses: klever1988/cachewrtbuild@main
      with:
         ccache: 'true'
         mixkey: '360T7-hanwckf'
         toolchain: 'true'
         skip: 'true'
         clean: ${{github.event.inputs.clean}}
         prefix: ${{ github.workspace }}/openwrt

    - name: Compile the firmware
      id: compile
      run: |
         cp ./glinet4.x/pkg_config/gl_pkg_config_mt7981_mt3000.mk  ./glinet4.x/mt7981/gl_pkg_config.mk
         ./scripts/gen_config.py target_mt7981_360t7-108M glinet_depends
         echo -e "$(nproc) thread compile"
         make -j$(nproc) || make -j1 V=s
         echo "release_tag=360T7-GL-OpenWrt-mini-$(date +%Y.%m.%d)" >> $GITHUB_ENV
         echo "release_name=360T7-GL-OpenWrt-mini" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && !cancelled()
      with:
         name: 360T7-GL-OpenWrt-$(date +%Y.%m.%d)
         path: openwrt/bin

    - name: Organize files
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
         echo "FIRMWARE=$PWD" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
         name: ${{ env.release_name }}
         tag_name: ${{ env.release_tag }}
         body: |
         GL.inet
         files: ${{ env.FIRMWARE }}/*

    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
