name: 360V6-ASUS

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      clean:
         description: 'clean ccache'
         default: 'false'

  #schedule:
  #- cron: 0 17 * * 1

env:
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      
    steps:
    
    - name: Prepare environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
         sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
         sudo timedatectl set-timezone "$TZ"
         sudo mkdir -p /doc
         sudo chown $USER:$GROUPS /doc
    
    - name: Clone source code
      working-directory: /doc
      run: |
         df -hT $PWD
         git clone https://github.com/stkuroneko/asuswrt-ipq6018.git
         git clone https://github.com/SWRT-dev/qca-toolchains
         ln -sf /doc/qca-toolchains $GITHUB_WORKSPACE/qca-toolchains
         cd qca-toolchains
         sudo ln -sf $(pwd)/openwrt-gcc520_musl.arm /opt/

    - name: Compile the firmware
      id: compile
      run: |
         cd ../asuswrt-ipq6018/release/src-qca-cypress
         make rt-360v6
         echo "release_tag=360V6-ASUS-$(date +%Y.%m.%d)" >> $GITHUB_ENV
         echo "release_name=ASUS" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && !cancelled()
      with:
         name: ASUS-$(date +%Y.%m.%d)
         path: release/src-qca-cypress/image
