name: Create-tag

on:
  workflow_dispatch:
 #schedule:
 #- cron: '0 20 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 生成标签
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        time=$(date +%Y.%m.%d-%H:%M)
        release_tag="test-$time"
        release_name="test"
        echo "release_name=$release_name" >> $GITHUB_OUTPUT
        echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT
