name: K2P-OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      clean:
         description: 'clean ccache'
         default: 'false'

  #schedule:
  #- cron: 0 17 * * 1

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: ./doc/config/K2P.config
  DIY_P1_SH: ./doc/diy/diy-360T7-hanwckf-1.sh
  DIY_P2_SH: ./doc/diy/diy-360T7-hanwckf-2.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
         sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
         sudo timedatectl set-timezone "$TZ"
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
    
    - name: Clone source code
      working-directory: /workdir
      run: |
         df -hT $PWD
         git clone $REPO_URL -b $REPO_BRANCH openwrt
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
    
    - name: Cache
      uses: klever1988/cachewrtbuild@main
      with:
         ccache: 'true'
         mixkey: 'K2P'
         toolchain: 'true'
         skip: 'true'
         clean: ${{github.event.inputs.clean}}
         prefix: ${{ github.workspace }}/openwrt
           
    - name: Load custom feeds
      run: |
         [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
         cat ./doc/config/ua2f.config >> openwrt/.config
         chmod +x $DIY_P1_SH
         cd openwrt
         $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a
      
    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
         [ -e files ] && mv files openwrt/files
         [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
         chmod +x $DIY_P2_SH
         cd openwrt
         $GITHUB_WORKSPACE/$DIY_P2_SH
        
    - name: Download package
      id: package
      run: |
         cd openwrt
         make defconfig
         make download -j16
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
         cd openwrt
         echo -e "$(nproc) thread compile"
         make -j$(nproc)
         echo "status=success" >> $GITHUB_OUTPUT

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
         name: K2P-OpenWrt
         path: openwrt/bin

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
         time=$(date +%Y.%m.%d)
         cd openwrt/bin/targets/*/*
         tar -cvf package.tar packages
         rm -rf feeds.buildinfo
         rm -rf *kernel*
         rm -rf *.manifest
         rm -rf sha256sums
         rm -rf version.buildinfo
         mv *sysupgrade.bin K2P-OpenWrt-sysupgrade-$time.bin
         mv *factory.bin K2P-OpenWrt-factory-$time.bin
         echo "FIRMWARE=$PWD" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
         time=$(date +%Y.%m.%d)
         Dtime=$(date +%Y.%m.%d-%H:%M)
         release_tag="K2P-OpenWrt-$time"
         release_name="K2P-OpenWr-$Dtime"
         echo "Gateway：192.168.50.1
         Password：password
         Application：mwan3，ramfree，ua2f" >> release.txt
         echo "release_name=$release_name" >> $GITHUB_OUTPUT
         echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
         echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
      with:
         name: ${{ steps.tag.outputs.release_name }} 
         tag_name: ${{ steps.tag.outputs.release_tag }}
         body_path: release.txt
         files: ${{ env.FIRMWARE }}/*

    - name: Email notification
      uses: dawidd6/action-send-mail@v3
      if: steps.compile.outputs.status == 'success' && !cancelled()
      with:
         server_address: smtp.163.com
         server_port: 465
         username: ${{ secrets.MAILUSERNAME }}
         password: ${{ secrets.MAILPASSWORD }}
         subject: 🎉Compilation succeeded🎉
         body: https://github.com/hkk666/360T7/releases
         to: ${{ secrets.MAIL }}
         from: GitHub Actions For K2P OpenWrt
         
    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
