name: Test

on:
  workflow_dispatch:
 #schedule:
 #- cron: '0 20 * * 1'
env:
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true

  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: 删除旧项目
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}