name: Test

on:
  workflow_dispatch:
 #schedule:
 #- cron: '0 20 * * 1'
env:
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true

  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
       
    - name: 'Send mail'
      uses: dawidd6/action-send-mail@v3
      with:
         server_address: smtp.163.com
         server_port: 465
         username: ${{ secrets.MAILUSERNAME }}
         password: ${{ secrets.MAILPASSWORD }}
         subject: Github Action
         body: 开始编译
         to: 1689726513@qq.com
         from: GitHub Actions
