name: Test

on:
  workflow_dispatch:
 #schedule:
 #- cron: '0 20 * * 1'
env:
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true

  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Delete old releases
      uses: docker://pivotalrabbitmq/delete-release-action:latest
      with:
         repository: rabbitmq/rabbitmq-java-tools-binaries-dev
         token: ${{ secrets.GITHUB_TOKEN }}
         keep-last-n: 2